import './globals.css'
import "@maptiler/sdk/dist/maptiler-sdk.css";
import { Inter } from 'next/font/google'
import Nav from '../components/Nav';
const inter = Inter({ subsets: ['latin'] })
import { Session } from 'next-auth';
import {NextAuthProvider} from 'components/NextAuthProvider';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }){

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider >
        <Nav>
      {children}
          </Nav>
          </NextAuthProvider>
      </body>
    </html>
  )
}
